# Generated by Django 2.2.2 on 2019-07-30 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skymiles_tracker', '0002_deal_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='deal',
            name='dollars',
            field=models.IntegerField(null=True),
        ),
    ]
